### ISSUE TITLE
Updating SSL/TLS certificate

### ISSUE THREAD

**Issue by jwoll** [jamf/JAWA#13]
Hello!

If I need to update my SSL/TLS certificate and private key, what is the best way to accomplish this?

Thank you.

**Comment by ball42** [comment]
Howdy!

Great question - the certificate (jawa.crt) and key (jawa.key) are stored within the directory
`/etc/ssl/certs/`

To update, replace the files in that directory with the new cert & key, and then restart the nginx service
`systemctl restart nginx.service`

**Comment by jwoll** [comment]
Great! Thank you, it worked.
