### ISSUE TITLE
webhook-auth branch crons

### ISSUE THREAD

**Issue by jrhoads-unt** [jamf/JAWA#15]
It seems the crons on the webhook-auth branch are still using absolute paths instead of the new relative paths under the "data" folder. Is this expected to be fixed sometime?

**Comment by ball42** [comment]
Added relative paths to the cron methods in the main > dev > webhook-auth branch and tested OK. @jrhoads-unt please pull the recent versions of `new_cron_job.py` and `delete_cron_job.py` from that branch to test in your environment.  Thanks
