### ISSUE TITLE
DeviceAddedToDEP Jamf Event missing

### ISSUE THREAD

**Issue by kryptonit1** [jamf/JAWA#25]
The **DeviceAddedToDEP** Jamf Event (https://developer.jamf.com/developer-guide/docs/webhooks#deviceaddedtodep) is missing in the dropdown menu when creating a new Jamf Pro Webhook. Would be nice if it was added.

**Comment by ball42** [comment]
Good catch! After testing & review, I noticed that the `SmartGroupUserMembershipChange` event was missing as well - each will be added to the dropdown in the v3.0.2 release.

**Comment by ball42** [comment]
Fixed in v3.0.2.  Thank you for the report, @kryptonit1
