### ISSUE TITLE
RHEL installer modifies the default nginx.conf

### ISSUE THREAD

**Issue by UniversalSuperBox** [jamf/JAWA#31]
I've noticed that the installer script for RHEL and CentOS modifies the default nginx.conf:

https://github.com/jamf/JAWA/blob/fbfdaf17b4f2d1370a92f396a2df927bcf1681e7/bin/rhel_installer.sh#L331-L334

Modifying the default config file could cause problems with multi-application deployments or existing proxy servers.

Instead, this script should act similar to Ubuntu with a small tweak. In Ubuntu, nginx modular configurations are loaded from `/etc/nginx/conf.d/*.conf` and `/etc/nginx/sites-enabled/*.conf`; the latter is loaded to provide a similar interface to Apache2 in Debian and Ubuntu. In RHEL, only `/etc/nginx/conf.d/*.conf` is loaded by default. This comes from the default config file's line `include /etc/nginx/conf.d/*.conf;`.

Therefore, JAWA should place [its modular configuration](https://github.com/jamf/JAWA/blob/fbfdaf17b4f2d1370a92f396a2df927bcf1681e7/bin/rhel_installer.sh#L374-L403) inside the `/etc/nginx/conf.d/` directory.

**Comment by ball42** [comment]
Good point, and thanks for the insight & tip.  Initial testing of the proposed changes were successful, so the RHEL installer will be updated accordingly.  Thanks again

**Comment by ball42** [comment]
resolved in #46
