### ISSUE TITLE
Problems launching JAWA 3.0.2 with newer Python

### ISSUE THREAD

**Issue by kryptonit1** [jamf/JAWA#36]
I've tried to get JAWA 3.0.2 to launch with a newer version of Python installed (3.9 or 3.10) on Ubuntu 18.04.

Sep 12 10:40:53 jawa python3[3142]:   File "/usr/local/bin/jawa/app.py", line 5, in <module>
Sep 12 10:40:53 jawa systemd[1]: jawa.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 10:40:53 jawa systemd[1]: jawa.service: Failed with result 'exit-code'.
Sep 12 10:40:54 jawa systemd[1]: jawa.service: Service hold-off time over, scheduling restart.
Sep 12 10:40:54 jawa systemd[1]: jawa.service: Scheduled restart job, restart counter is at 1.

Am I doing something wrong?

**Comment by ball42** [comment]
It should work...I just upgraded my default Python3 to 3.9 on an Ubuntu 18.04 test server and ran through the installer, but not without difficulty. The python3.9 package didn't include pip, so I had to run `apt install python3.9-full`, install pip manually (`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`), and symlink python3 -> python3.9 in order for the installer to use python3.9 for creating the venv + python3.9 pip for installing requirements.  Can you verify that you have pip by running:

`/path/to/your/python3.9 -m pip help`

If you do have pip and a venv for JAWA, can you please run the following command and provide the traceback? 

`sudo -u jawa "/usr/local/jawa/venv/bin/python3" /usr/local/jawa/app.py`

**Comment by kryptonit1** [comment]
Thank you! I’ll try this as soon as possible, but it might take a little while.

**Comment by kryptonit1** [comment]
I was able to solve the problem with the help of your instructions. Thank you!
